/**
 * PinScope convergence engine — STATUS.md renderer (pure core).
 *
 * `renderStatus(loop, matrixById) → string`. No I/O.
 */

export function renderStatus(loop, matrixById) {
  const m = loop.metric || {};
  const manualPending = m.manual_pending || 0;
  const out = [];
  const P = (s = '') => out.push(s);

  P('<!-- GENERATED by lib/render-status.mjs from loop.json — do not hand-edit -->');
  P('# PinScope Convergence — STATUS');
  P();
  P('> Live dashboard for the PinScope self-healing loop (`PS-R{N}`).');
  P(`> **North-Star:** \`${loop.north_star}\` — version ${loop.north_star_version}, **FROZEN**.`);
  P(`> **Loop status:** **${loop.loop_status}** · round ${loop.round}.`);
  P('> Generated from `loop.json`. See `LOOP.md` and `CONVERGENCE-REPORT.md`.');
  P();
  P('## Convergence metric');
  P();
  P('`closed_AC / total_AC` — monotonically non-decreasing every round.');
  P();
  P('| Round | Closed | Total | %   | Notes |');
  P('|-------|--------|-------|-----|-------|');
  for (const h of loop.metric_history || []) {
    const label = h.round === 0 ? 'baseline' : `PS-R${h.round}`;
    P(`| ${label} | ${h.closed} | ${m.total} | ${h.pct}% | ${h.note || ''} |`);
  }
  P();
  P('## Status legend');
  P();
  P("- **CLOSED** — verified passing by the AC's `verify:` check.");
  P('- **BLOCKED** — implementation built + test authored, but the `verify:`');
  P('  needs an environment unavailable here (browser engine, or a `~/.claude/`');
  P('  APEX install). Closeable verbatim on a capable CI.');
  P('- **MANUAL_PENDING** — a `manual`-kind AC whose environment is now');
  P('  available; awaits an explicit `loop-state.mjs manual-attest`.');
  P('- **OPEN** — unresolved gap.');
  P('- **BACKLOG** — P3, explicitly deferred by user decision.');
  P();
  P('## Convergence condition');
  P();
  if (m.open === 0) {
    P(`**MET** — zero OPEN criteria; ${m.closed} CLOSED, ${m.blocked} BLOCKED` +
      (manualPending ? `, ${manualPending} MANUAL_PENDING.` : '.'));
  } else {
    P(`Not yet met — **${m.open}** OPEN criteria remain.`);
  }
  P();
  P('## Circuit breaker log');
  P();
  const stalled = (loop.findings || []).filter(
    (f) => f.status === 'OPEN' && (f.rounds_unchanged || 0) >= 3,
  );
  if (loop.loop_status === 'BREAKER_TRIPPED' || stalled.length > 0) {
    P('**TRIPPED** — the loop is halted; convergence is not claimed.');
    for (const f of stalled) {
      P(`- finding \`${f.id}\` (${f.ac}) unchanged for ${f.rounds_unchanged} rounds`);
    }
  } else {
    P('_(empty — no stalls)_');
  }
  for (const ev of loop.breaker_log || []) {
    P(`- round ${ev.round}: ${ev.event}${ev.at ? ` (${ev.at})` : ''}`);
  }
  P();
  P('## Acceptance Criteria ledger');
  P();
  P('| AC      | Phase | Sev | Status        | Round |');
  P('|---------|-------|-----|---------------|-------|');
  const ids = Object.keys(loop.criteria || {}).sort();
  for (const id of ids) {
    const c = loop.criteria[id];
    const meta = matrixById[id] || {};
    const status = (c.status || 'OPEN').padEnd(13);
    P(`| ${id} | ${meta.phase || '?'}    | ${meta.severity || '?'}  | ${status} | ${c.round ?? '—'}     |`);
  }
  P();
  P(
    `**Total: ${m.total} ACs · ${m.closed} CLOSED · ${m.open} OPEN · ` +
      `${m.blocked} BLOCKED` +
      (manualPending ? ` · ${manualPending} MANUAL_PENDING` : '') +
      ` · ${m.pct}% converged**`,
  );
  P();

  const blocked = ids.filter((id) => loop.criteria[id].status === 'BLOCKED');
  if (blocked.length > 0) {
    P(`## The ${blocked.length} BLOCKED criteria`);
    P();
    P('Implemented + test-authored; the SPEC `verify:` cannot run in this');
    P('environment. No PinScope code change unblocks them — a capable CI does.');
    P();
    for (const id of blocked) {
      const c = loop.criteria[id];
      P(`- **${id}** — \`${c.blocked_reason || 'environment'}\`; unblocks on ${c.unblocks_on || 'a capable CI'}.`);
    }
    P();
  }

  P('## Round history');
  P();
  for (const h of loop.metric_history || []) {
    if (h.round === 0) continue;
    P(`- **PS-R${h.round}** — ${h.note || ''} ${h.closed}/${m.total} (${h.pct}%).`);
  }
  P();
  if (m.open === 0) {
    P('## Loop complete');
    P();
    P('The PS-R{N} self-healing convergence loop has reached its terminal');
    P(`condition: ${m.closed}/${m.total} verified (${m.pct}%), ${m.blocked} environment-BLOCKED, 0 OPEN.`);
    P();
  }

  return `${out.join('\n')}`;
}
