#!/usr/bin/env node
/**
 * PinScope convergence — render STATUS.md from loop.json.
 *
 *   node render-status.mjs
 *
 * STATUS.md is a GENERATED artifact: every number is computed from
 * loop.json, never hand-typed. This removes the per-round hand-edit that
 * was the most error-prone step of the original loop.
 *
 * Exit: 0 ok · 1 bad input.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const LIB = path.dirname(fileURLToPath(import.meta.url));
const CONV = path.dirname(LIB);

function load(name) {
  const p = path.join(CONV, name);
  if (!existsSync(p)) {
    console.error(`render-status: ${name} not found`);
    process.exit(1);
  }
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch (e) {
    console.error(`render-status: ${name} is not valid JSON — ${e.message}`);
    process.exit(1);
  }
}

const loop = load('loop.json');
const matrix = load('ac-matrix.json');
const meta = {};
for (const c of matrix.criteria) meta[c.id] = c;

const m = loop.metric;
const out = [];
const P = (s = '') => out.push(s);

P('<!-- GENERATED by lib/render-status.mjs from loop.json — do not hand-edit -->');
P('# PinScope Convergence — STATUS');
P();
P('> Live dashboard for the PinScope self-healing loop (`PS-R{N}`).');
P(`> **North-Star:** \`${loop.north_star}\` — version ${loop.north_star_version}, **FROZEN**.`);
P(`> **Loop status:** **${loop.loop_status}** · round ${loop.round}.`);
P('> Generated from `loop.json`. See `LOOP.md` and `CONVERGENCE-REPORT.md`.');
P();
P('## Convergence metric');
P();
P('`closed_AC / total_AC` — monotonically non-decreasing every round.');
P();
P('| Round | Closed | Total | %   | Notes |');
P('|-------|--------|-------|-----|-------|');
for (const h of loop.metric_history || []) {
  const label = h.round === 0 ? 'baseline' : `PS-R${h.round}`;
  P(`| ${label} | ${h.closed} | ${m.total} | ${h.pct}% | ${h.note || ''} |`);
}
P();
P('## Status legend');
P();
P("- **CLOSED** — verified passing by the AC's `verify:` check.");
P('- **BLOCKED** — implementation built + test authored, but the `verify:`');
P('  needs an environment unavailable here (browser engine, or a `~/.claude/`');
P('  APEX install). Closeable verbatim on a capable CI.');
P('- **OPEN** — unresolved gap.');
P('- **BACKLOG** — P3, explicitly deferred by user decision.');
P();
P('## Convergence condition');
P();
if (m.open === 0) {
  P(`**MET** — zero OPEN criteria; every AC is CLOSED (${m.closed}) or BLOCKED (${m.blocked}).`);
} else {
  P(`Not yet met — **${m.open}** OPEN criteria remain.`);
}
P();
P('## Circuit breaker log');
P();
const stalled = (loop.findings || []).filter(
  (f) => f.status === 'OPEN' && (f.rounds_unchanged || 0) >= 3,
);
if (loop.loop_status === 'BREAKER_TRIPPED' || stalled.length > 0) {
  P('**TRIPPED** — the loop is halted; convergence is not claimed.');
  for (const f of stalled) {
    P(`- finding \`${f.id}\` (${f.ac}) unchanged for ${f.rounds_unchanged} rounds`);
  }
} else {
  P('_(empty — no stalls)_');
}
P();
P('## Acceptance Criteria ledger');
P();
P('| AC      | Phase | Sev | Status  | Round |');
P('|---------|-------|-----|---------|-------|');
const ids = Object.keys(loop.criteria).sort();
for (const id of ids) {
  const c = loop.criteria[id];
  const mm = meta[id] || {};
  const status = (c.status || 'OPEN').padEnd(7);
  P(`| ${id} | ${mm.phase || '?'}    | ${mm.severity || '?'}  | ${status} | ${c.round ?? '—'}     |`);
}
P();
P(
  `**Total: ${m.total} ACs · ${m.closed} CLOSED · ${m.open} OPEN · ` +
    `${m.blocked} BLOCKED · ${m.pct}% converged**`,
);
P();

const blocked = ids.filter((id) => loop.criteria[id].status === 'BLOCKED');
if (blocked.length > 0) {
  P(`## The ${blocked.length} BLOCKED criteria`);
  P();
  P('Implemented + test-authored; the SPEC `verify:` cannot run in this');
  P('environment. No PinScope code change unblocks them — a capable CI does.');
  P();
  for (const id of blocked) {
    const c = loop.criteria[id];
    P(`- **${id}** — \`${c.blocked_reason || 'environment'}\`; unblocks on ${c.unblocks_on || 'a capable CI'}.`);
  }
  P();
}

P('## Round history');
P();
for (const h of loop.metric_history || []) {
  if (h.round === 0) continue;
  P(`- **PS-R${h.round}** — ${h.note || ''} ${h.closed}/${m.total} (${h.pct}%).`);
}
P();
if (m.open === 0) {
  P('## Loop complete');
  P();
  P('The PS-R{N} self-healing convergence loop has reached its terminal');
  P(`condition: ${m.closed}/${m.total} verified (${m.pct}%), ${m.blocked} environment-BLOCKED, 0 OPEN.`);
  P();
}

writeFileSync(path.join(CONV, 'STATUS.md'), `${out.join('\n')}`);
console.log(`render-status: STATUS.md written — ${m.closed}/${m.total} CLOSED (${m.pct}%)`);
process.exit(0);
